# Generated by Django 5.1.5 on 2025-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='unlocked',
            new_name='is_unlocked',
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
