# Generated by Django 5.1.5 on 2025-01-31 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_unlocked_course_is_unlocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(default='Réponse par défaut', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='education.quiz')),
            ],
        ),
    ]
